<?php
define('ABSPATH',__DIR__.'/');class Term{public function __construct(public int $term_id,public string $name,public string $slug=''){}}
function wp_check_invalid_utf8($v){return$v;}function mb_strtolower($v){return strtolower($v);}function current_time($t){return'2026-07-05 10:00:00';}function absint($v){return abs((int)$v);}function sanitize_text_field($v){return trim((string)$v);}function sanitize_textarea_field($v){return trim((string)$v);}function esc_url_raw($v){return trim((string)$v);}function remove_accents($v){return iconv('UTF-8','ASCII//TRANSLIT',$v)?:$v;}function get_terms($a){return$a['taxonomy']==='category'?[new Term(10,'Movilidad')]:[new Term(20,'Diseño automotriz','automovil')];}function is_wp_error($v){return false;}
require_once dirname(__DIR__).'/includes/class-radar-importer.php';function ok($c,$m){if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo"OK: $m\n";}
function jsonBrief(int $id,string $keyword):string{return json_encode(['sistema'=>'radar-editorial-ideasdi','destino'=>'gerizim-wp','version_exportacion'=>'1.1','fecha_exportacion'=>'2026-07-04T09:00:00Z','brief'=>['id'=>$id,'keyword_principal'=>$keyword,'responsable'=>'Marca','responsable_url'=>'https://example.com','fuente_oficial'=>'https://example.com/news','tipo_pieza'=>'Actualidad','categoria_wp'=>'Movilidad','etiquetas_wp'=>['Diseño automotriz'],'tag_principal'=>'Diseño automotriz'],'contenido_editorial'=>['hecho_base'=>'Hecho base suficiente para la prueba.','angulo_editorial'=>'Ángulo editorial de prueba.'],'hallazgo'=>['id'=>$id+100]]);}
$wid='idg_88888888-8888-4888-8888-888888888888';$originalDate='2026-07-04T10:00:00Z';$key='gerizim_imported:901:'.$wid;$current=['workflow_id'=>$wid,'radar_source'=>'radar-editorial-ideasdi','radar_brief_id'=>901,'radar_imported_at'=>'2026-07-04 05:00:00','radar_imported_at_utc'=>$originalDate,'radar_import_persisted'=>true,'radar_import_identity'=>hash('sha256','radar-editorial-ideasdi|901|'.$wid),'traceability_gerizim_imported_key'=>$key,'traceability_gerizim_imported_status'=>'sent','keyword'=>'Anterior'];
$same=IDG_Radar_Importer::import_from_json_string(jsonBrief(901,'Mismo brief actualizado'),$current);ok(!empty($same['success']),'mismo brief puede actualizar datos editoriales');$w=$same['workflow'];ok(($w['workflow_id']??'')===$wid,'mismo brief conserva workflow');ok(($w['radar_imported_at_utc']??'')===$originalDate,'mismo brief conserva fecha original');ok(($w['traceability_gerizim_imported_key']??'')===$key,'mismo brief conserva clave idempotente');
$historicalWithoutDate=$current;unset($historicalWithoutDate['radar_imported_at'],$historicalWithoutDate['radar_imported_at_utc']);$blocked=IDG_Radar_Importer::import_from_json_string(jsonBrief(901,'Mismo brief sin fecha'),$historicalWithoutDate);ok(empty($blocked['success'])&&($blocked['reason']??'')==='invalid_import_occurred_at','mismo brief histórico sin fecha original queda bloqueado');
$different=IDG_Radar_Importer::import_from_json_string(jsonBrief(902,'Brief diferente'),[]);ok(!empty($different['success']),'brief diferente puede prepararse para workflow nuevo');$nw=$different['workflow'];ok(empty($nw['workflow_id']),'brief diferente no hereda workflow');ok(empty($nw['radar_imported_at_utc'])&&empty($nw['traceability_gerizim_imported_key']),'brief diferente no hereda fecha ni trazabilidad');
$admin=file_get_contents(dirname(__DIR__).'/includes/class-admin-page.php');ok(str_contains($admin,'$different_radar_brief')&&str_contains($admin,"IDG_Workflow_Orchestrator::create(\$data, 'radar')"),'administración crea workflow nuevo para otra identidad');ok(str_contains($admin,'restore_radar_partial_reset_snapshot'),'flujo anterior se restaura si hubo reinicio parcial');
echo"PASS radar identity mock\n";
