<?php
$root = dirname(__DIR__);
$read = static fn(string $path): string => file_get_contents($root . '/' . $path) ?: '';
$files = [
    'main' => $read('ideasdi-redaccion-gerizim.php'),
    'trace' => $read('includes/class-traceability.php'),
    'outbox' => $read('includes/class-traceability-outbox.php'),
    'recapture' => $read('includes/class-traceability-recapture.php'),
    'admin_page' => $read('includes/class-admin-page.php'),
    'post' => $read('includes/class-post-creator.php'),
    'runner' => $read('includes/class-job-runner.php'),
    'client' => $read('includes/class-traceability-client.php'),
    'logger' => $read('includes/class-logger.php'),
    'capture_test' => $read('tests/traceability-capture-mock.php'),
    'provenance_test' => $read('tests/traceability-provenance-disabled-mock.php'),
    'reimport_test' => $read('tests/radar-reimport-after-partial-reset-mock.php'),
    'snapshot_test' => $read('tests/radar-partial-reset-snapshot-mock.php'),
    'recapture_test' => $read('tests/traceability-recapture-mock.php'),
    'marker_test' => $read('tests/traceability-failure-marker-recovery-mock.php'),
    'schema_test' => $read('tests/traceability-schema-mock.php'),
    'outbox_test' => $read('tests/traceability-outbox-integration-mock.php'),
    'reflection_test' => $read('tests/traceability-reflection-failure-mock.php'),
    'client_test' => $read('tests/traceability-client-mock.php'),
    'url_test' => $read('tests/traceability-url-policy-mock.php'),
    'defaults_test' => $read('tests/traceability-defaults-mock.php'),
    'logger_test' => $read('tests/traceability-logger-mock.php'),
    'smoke_test' => $read('tests/plugin-load-smoke.php'),
];
function has(string $text, string $needle): bool { return str_contains($text, $needle); }
function accept(int $number, bool $condition, string $label): void {
    if (!$condition) { fwrite(STDERR, sprintf("FAIL A%02d: %s\n", $number, $label)); exit(1); }
    echo sprintf("OK A%02d: %s\n", $number, $label);
}

$cases = [
  1 => [has($files['capture_test'], 'persistencia real guarda fecha UTC'), 'Nueva identidad Radar recibe fecha de importación'],
  2 => [has($files['provenance_test'], 'captura apagada no impide persistir procedencia'), 'Captura apagada conserva radar_imported_at_utc'],
  3 => [has($files['capture_test'], 'mismo brief conserva fecha original'), 'Mismo brief conserva la fecha'],
  4 => [has($files['reimport_test'], 'mismo brief histórico sin fecha original queda bloqueado'), 'Mismo brief histórico sin fecha no recibe now'],
  5 => [has($files['provenance_test'], 'fecha local histórica se convierte de forma fiable a UTC'), 'Fecha local histórica se convierte a UTC'],
  6 => [has($files['capture_test'], 'fecha original inválida bloquea reconstrucción'), 'Fecha inválida produce blocked'],
  7 => [has($files['capture_test'], 'reconstrucción anterior al corte se excluye'), 'Reconstrucción anterior al corte se rechaza'],
  8 => [has($files['reimport_test'], 'brief diferente puede prepararse para workflow nuevo'), 'Brief diferente crea workflow nuevo'],
  9 => [has($files['reimport_test'], 'flujo anterior se restaura si hubo reinicio parcial'), 'Workflow anterior queda intacto'],
 10 => [has($files['reimport_test'], 'mismo brief conserva workflow'), 'Mismo brief conserva workflow'],
 11 => [has($files['reimport_test'], 'mismo brief conserva clave idempotente'), 'Mismo brief conserva clave'],
 12 => [has($files['outbox_test'], 'occurred_at distinto produce conflicto'), 'Payload contradictorio produce conflicto'],
 13 => [has($files['capture_test'], 'actualización recurrente no genera outbox'), 'Actualización recurrente no genera eventos'],
 14 => [has($files['snapshot_test'], 'fallo de almacenamiento se devuelve de forma explícita'), 'Fallo de add_option aborta reinicio'],
 15 => [has($files['snapshot_test'], 'snapshot durable conserva hash'), 'Snapshot guarda hash'],
 16 => [has($files['snapshot_test'], 'snapshot no se borra tras fallo de restauración'), 'Fallo de restauración conserva snapshot'],
 17 => [has($files['snapshot_test'], 'restauración incompleta se detecta'), 'Restauración parcial no se considera exitosa'],
 18 => [has($files['snapshot_test'], 'snapshot se borra solo después de confirmar restauración'), 'Snapshot se elimina solo tras verificación completa'],
 19 => [has($files['recapture_test'], 'segunda intención concurrente no sobrescribe la primera'), 'Dos recapturas simultáneas no se sobrescriben'],
 20 => [has($files['recapture_test'], 'cursor aislado no cuenta como intención pendiente'), 'Solo el cursor produce conteo cero'],
 21 => [has($files['recapture_test'], 'intención se elimina solo después de limpieza verificada'), 'Intención compatible se elimina'],
 22 => [has($files['recapture_test'], 'intención conflictiva no se elimina'), 'Intención conflictiva se conserva'],
 23 => [has($files['marker_test'], 'marca alternativa queda visible para diagnóstico'), 'Fallo de persistencia queda visible'],
 24 => [has($files['marker_test'], 'outbox recupera publicación desde meta persistida'), 'Publicación puede reconstruirse desde meta persistida'],
 25 => [has($files['schema_test'], "'dbdelta_error'"), 'Error de dbDelta bloqueado'],
 26 => [has($files['schema_test'], "'partial'"), 'Tabla parcial bloqueada'],
 27 => [has($files['schema_test'], 'unset($c[\'reflection_last_error\'])'), 'Columna ausente detectada'],
 28 => [has($files['schema_test'], "'missing_index'"), 'Índice único ausente detectado'],
 29 => [has($files['schema_test'], 'no actualiza versión'), 'Versión no se actualiza con esquema incompleto'],
 30 => [has($files['outbox'], 'if (!self::schema_ready())') && has($files['outbox'], 'traceability_schema_incomplete'), 'Cola no procesa con esquema inválido'],
 31 => [has($files['outbox_test'], 'for($i=0;$i<30;$i++'), 'Más hijos bloqueados que tamaño de lote'],
 32 => [has($files['outbox_test'], 'consulta anti-starvation entrega raíz lista posterior'), 'Evento listo posterior se procesa'],
 33 => [has($files['outbox_test'], 'cadena completa enviada'), 'Dependencia enviada libera hijo'],
 34 => [has($files['outbox_test'], 'ocho intentos terminan failed'), 'Octavo fallo produce retry_limit_reached'],
 35 => [has($files['outbox_test'], 'reconciliación está paginada'), 'Reconciliación cubre más de un lote'],
 36 => [has($files['outbox_test'], 'cursor de reconciliación llega a filas de lotes posteriores'), 'Cursor llega a filas posteriores'],
 37 => [has($files['outbox_test'], 'filas terminales ya sincronizadas no se recorren indefinidamente'), 'Filas terminales no se recorren indefinidamente'],
 38 => [has($files['outbox_test'], 'reconciliación excluye sending con lock activo'), 'Fila sending con lock no se refleja'],
 39 => [has($files['outbox_test'], 'cambio sending a sent durante sincronización no marca reflejo'), 'Cambio concurrente sending a sent no marca reflejo obsoleto'],
 40 => [has($files['reflection_test'], 'fallo de update_option deja pendiente'), 'Fallo de update_option deja pendiente'],
 41 => [has($files['reflection_test'], 'fallo de update_post_meta deja pendiente'), 'Fallo de update_post_meta deja pendiente'],
 42 => [has($files['client_test'], "'201-result'"), 'result aceptado'],
 43 => [has($files['client_test'], "'201-code'"), 'code aceptado temporalmente'],
 44 => [has($files['client_test'], "'wrong-key'"), 'Clave distinta rechazada'],
 45 => [has($files['client_test'], "'200-result'"), 'already_recorded queda sent'],
 46 => [has($files['url_test'], 'HTTP productivo rechazado'), 'HTTP productivo inseguro rechazado'],
 47 => [has($files['url_test'], 'HTTP localhost permitido'), 'HTTP local de testing permitido'],
 48 => [has($files['logger_test'], 'sensitive value persisted') && has($files['client_test'], 'token redactado de error'), 'Token no aparece en logs'],
 49 => [has($files['defaults_test'], 'PASS traceability defaults'), 'Plugin arranca con trazabilidad apagada'],
 50 => [has($files['smoke_test'], 'PASS plugin load smoke') && has($files['runner'], 'run_generate'), 'Flujo editorial actual continúa'],
 51 => [has($files['post'], "'post_status' => 'pending'"), 'Entrada se crea en pending'],
 52 => [has($files['client_test'], 'radar.example.test') && !has($files['client_test'], 'radar.ideasdi.com'), 'Pruebas no generan conexiones reales'],
 53 => [has($files['post'], 'create_pending_post') && has($files['runner'], 'run_editorial'), 'Componentes editoriales protegidos permanecen disponibles'],
];

foreach ($cases as $number => [$condition, $label]) { accept($number, $condition, $label); }
echo "PASS RC1.5.6 regression acceptance 53/53\n";
