<?php
define('ABSPATH',__DIR__.'/');define('IDG_TRACEABILITY_DB_VERSION','1.2.0');define('ARRAY_A','ARRAY_A');
final class PQ{public function __construct(public string $sql,public array $args){}}
final class DB{
 public string $prefix='wp_';public string $last_error='';public array $rows=[];public int $next=1;
 public function prepare($q,...$a):PQ{return new PQ($q,$a);}public function get_charset_collate():string{return'';}
 private function sql($q):string{return preg_replace('/\s+/',' ',trim($q instanceof PQ?$q->sql:(string)$q));}private function args($q):array{return$q instanceof PQ?$q->args:[];}
 private function columns():array{return['id'=>['bigint(20) unsigned','NO'],'idempotency_key'=>['varchar(191)','NO'],'event_type'=>['varchar(64)','NO'],'payload_json'=>['longtext','NO'],'status'=>['varchar(20)','NO'],'attempts'=>['smallint(5) unsigned','NO'],'next_attempt_at'=>['datetime','YES'],'last_http_status'=>['smallint(5) unsigned','YES'],'last_error'=>['varchar(500)','NO'],'last_transport_error'=>['varchar(500)','NO'],'created_at'=>['datetime','NO'],'updated_at'=>['datetime','NO'],'sent_at'=>['datetime','YES'],'dependency_key'=>['varchar(191)','NO'],'lock_token'=>['varchar(64)','NO'],'locked_at'=>['datetime','YES'],'reflection_synced_at'=>['datetime','YES'],'reflection_last_error'=>['varchar(500)','NO'],'reflection_attempts'=>['smallint(5) unsigned','NO'],'reflection_last_attempt_at'=>['datetime','YES']];}
 public function get_var($q){$s=$this->sql($q);if(str_contains($s,'SHOW TABLES LIKE'))return'wp_idg_traceability_outbox';if(str_contains($s,'MAX(sent_at)')){$a=array_filter(array_column($this->rows,'sent_at'));return$a?max($a):'';}if(str_contains($s,"WHERE last_error <> ''")){foreach(array_reverse($this->rows,true)as$r)if($r['last_error']!=='')return$r['last_error'];}return null;}
 public function get_row($q,$m=null):?array{$s=$this->sql($q);$a=$this->args($q);if(str_contains($s,'WHERE idempotency_key = %s')){foreach($this->rows as$r)if($r['idempotency_key']===(string)$a[0])return$r;}if(str_contains($s,'WHERE id = %d'))return$this->rows[(int)$a[0]]??null;return null;}
 public function get_col($q):array{$s=$this->sql($q);$a=$this->args($q);if(!str_contains($s,'SELECT child.id'))return[];$now=(string)$a[0];$limit=(int)$a[1];$ids=[];foreach($this->rows as$id=>$r){if(!in_array($r['status'],['queued','retry'],true))continue;if($r['next_attempt_at']!==null&&$r['next_attempt_at']>$now)continue;if($r['lock_token']!==''||$r['locked_at']!==null)continue;if($r['dependency_key']!==''){$p=$this->find($r['dependency_key']);if(!$p||$p['status']!=='sent')continue;}$ids[]=$id;}sort($ids);return array_slice($ids,0,$limit);}
 private function find(string $k):?array{foreach($this->rows as$r)if($r['idempotency_key']===$k)return$r;return null;}
 public function get_results($q,$m=null):array{$s=$this->sql($q);$a=$this->args($q);
  if(str_contains($s,'SHOW COLUMNS'))return array_map(fn($n,$v)=>['Field'=>$n,'Type'=>$v[0],'Null'=>$v[1]],array_keys($this->columns()),array_values($this->columns()));
  if(str_contains($s,'SHOW INDEX')){$defs=[['PRIMARY',0,['id']],['idempotency_key',0,['idempotency_key']],['status_next_attempt',1,['status','next_attempt_at','id']],['dependency_key',1,['dependency_key']],['locked_at',1,['locked_at']],['reflection_sync',1,['reflection_synced_at','updated_at','id']]];$o=[];foreach($defs as[$n,$nu,$cs])foreach($cs as$i=>$c)$o[]=['Key_name'=>$n,'Non_unique'=>$nu,'Seq_in_index'=>$i+1,'Column_name'=>$c];return$o;}
  if(str_contains($s,'GROUP BY status')){$c=[];foreach($this->rows as$r)$c[$r['status']]=($c[$r['status']]??0)+1;foreach($c as$k=>$v)$o[]=['status'=>$k,'total'=>$v];return$o??[];}
  if(str_contains($s,"dependency_key<>''")||str_contains($s,"dependency_key <> ''")){$after=(int)$a[0];$limit=(int)$a[1];return array_slice(array_values(array_filter($this->rows,fn($r)=>$r['id']>$after&&$r['dependency_key']!==''&&in_array($r['status'],['queued','retry','blocked'],true))),0,$limit);}
  if(str_contains($s,"status='blocked' AND last_error=%s")){$after=(int)$a[0];$err=(string)$a[1];$limit=(int)$a[2];return array_slice(array_values(array_filter($this->rows,fn($r)=>$r['id']>$after&&$r['status']==='blocked'&&$r['last_error']===$err&&$r['locked_at']===null)),0,$limit);}
  if(str_contains($s,'reflection_synced_at IS NULL OR reflection_synced_at < updated_at')){$after=(int)$a[0];$limit=(int)$a[1];return array_slice(array_values(array_filter($this->rows,fn($r)=>$r['id']>$after&&($r['reflection_synced_at']===null||$r['reflection_synced_at']<$r['updated_at'])&&!($r['status']==='sending'&&($r['lock_token']!==''||$r['locked_at']!==null)))),0,$limit);}
  if(str_contains($s,"status IN ('failed','blocked')")){$limit=(int)end($a);return array_slice(array_values(array_filter($this->rows,fn($r)=>in_array($r['status'],['failed','blocked'],true))),0,$limit);}return[];}
 public function query($q){if(!$q instanceof PQ)return 0;$s=$this->sql($q);$a=$q->args;
  if(str_starts_with($s,'INSERT INTO')){[$key,$type,$json,$status,$next,$error,$created,$updated,$dep]=$a;foreach($this->rows as$r)if($r['idempotency_key']===$key)return 0;$id=$this->next++;$this->rows[$id]=['id'=>$id,'idempotency_key'=>$key,'event_type'=>$type,'payload_json'=>$json,'status'=>$status,'attempts'=>0,'next_attempt_at'=>$next,'last_http_status'=>null,'last_error'=>$error,'last_transport_error'=>'','created_at'=>$created,'updated_at'=>$updated,'sent_at'=>null,'dependency_key'=>$dep,'lock_token'=>'','locked_at'=>null,'reflection_synced_at'=>null,'reflection_last_error'=>'','reflection_attempts'=>0,'reflection_last_attempt_at'=>null];return 1;}
  if(str_contains($s,"SET status='sending'")){[$token,$locked,$updated,$id,$now]=$a;$id=(int)$id;if(!isset($this->rows[$id]))return 0;$r=&$this->rows[$id];if(!in_array($r['status'],['queued','retry'],true)||$r['lock_token']!==''||$r['locked_at']!==null||($r['next_attempt_at']!==null&&$r['next_attempt_at']>$now))return 0;$r['status']='sending';$r['lock_token']=$token;$r['locked_at']=$locked;$r['updated_at']=$updated;$r['reflection_synced_at']=null;return 1;}
  if(str_contains($s,"WHERE id=%d AND status='sending' AND lock_token=%s")){$id=(int)$a[count($a)-2];$token=(string)$a[count($a)-1];if(!isset($this->rows[$id])||$this->rows[$id]['status']!=='sending'||$this->rows[$id]['lock_token']!==$token)return 0;$r=&$this->rows[$id];if(str_contains($s,"status='sent'")){[$attempts,$http,$sent,$updated]=array_slice($a,0,4);$r['status']='sent';$r['attempts']=(int)$attempts;$r['last_http_status']=(int)$http;$r['sent_at']=$sent;$r['last_error']='';$r['last_transport_error']='';$r['next_attempt_at']=null;$r['updated_at']=$updated;}elseif(str_contains($s,"status='retry'")){[$attempts,$next,$http,$err,$terr,$updated]=array_slice($a,0,6);$r['status']='retry';$r['attempts']=(int)$attempts;$r['next_attempt_at']=$next;$r['last_http_status']=(int)$http;$r['last_error']=$err;$r['last_transport_error']=$terr;$r['updated_at']=$updated;}elseif(str_contains($s,"status='failed'")){[$attempts,$http,$err,$terr,$updated]=array_slice($a,0,5);$r['status']='failed';$r['attempts']=(int)$attempts;$r['last_http_status']=(int)$http;$r['last_error']=$err;$r['last_transport_error']=$terr;$r['next_attempt_at']=null;$r['updated_at']=$updated;}else{[$err,$updated]=array_slice($a,0,2);$r['status']='blocked';$r['last_error']=$err;$r['next_attempt_at']=null;$r['updated_at']=$updated;}$r['lock_token']='';$r['locked_at']=null;$r['reflection_synced_at']=null;return 1;}
  if(str_contains($s,"status IN ('queued','retry','blocked')")){[$err,$updated,$id]=$a;$id=(int)$id;if(!isset($this->rows[$id]))return 0;$r=&$this->rows[$id];if(!in_array($r['status'],['queued','retry','blocked'],true)||$r['lock_token']!==''||$r['locked_at']!==null)return 0;$r['status']='blocked';$r['last_error']=$err;$r['next_attempt_at']=null;$r['updated_at']=$updated;$r['reflection_synced_at']=null;return 1;}
  if(str_contains($s,"WHERE id=%d AND status='blocked'")){[$next,$updated,$id]=$a;$id=(int)$id;if(!isset($this->rows[$id]))return 0;$r=&$this->rows[$id];if($r['status']!=='blocked'||$r['lock_token']!==''||$r['locked_at']!==null)return 0;$r['status']='queued';$r['next_attempt_at']=$next;$r['last_error']='';$r['updated_at']=$updated;$r['reflection_synced_at']=null;return 1;}
  if(str_contains($s,"status IN ('failed','blocked')")){[$next,$updated,$id]=$a;$id=(int)$id;if(!isset($this->rows[$id]))return 0;$r=&$this->rows[$id];if(!in_array($r['status'],['failed','blocked'],true)||$r['lock_token']!==''||$r['locked_at']!==null)return 0;$r['status']='queued';$r['attempts']=0;$r['next_attempt_at']=$next;$r['last_error']='';$r['last_transport_error']='';$r['updated_at']=$updated;$r['reflection_synced_at']=null;return 1;}
  if(str_contains($s,'SET reflection_synced_at=%s')){[$sync,$attempted,$id,$status,$updated]=$a;$id=(int)$id;if(!isset($this->rows[$id])||$this->rows[$id]['status']!==$status||$this->rows[$id]['updated_at']!==$updated)return 0;$this->rows[$id]['reflection_synced_at']=$sync;$this->rows[$id]['reflection_last_error']='';$this->rows[$id]['reflection_attempts']=0;$this->rows[$id]['reflection_last_attempt_at']=$attempted;return 1;}
  if(str_contains($s,'SET reflection_last_error=%s')){[$err,$attempted,$id]=$a;$id=(int)$id;$this->rows[$id]['reflection_last_error']=$err;$this->rows[$id]['reflection_attempts']++;$this->rows[$id]['reflection_last_attempt_at']=$attempted;return 1;}
  if(str_contains($s,"WHERE status='sending' AND locked_at IS NOT NULL"))return 0;if(str_contains($s,"WHERE status='retry'"))return 0;return 0;}
}
$wpdb=new DB();$GLOBALS['wpdb']=$wpdb;$GLOBALS['options']=[];
class IDG_Traceability{public static array $scheduled=[];public static array $synced=[];public static string $mutateDuringSyncKey='';public static function delivery_enabled():bool{return true;}public static function delivery_configuration_valid():bool{return true;}public static function schedule_processing():void{self::$scheduled[]='now';}public static function schedule_at(int $t):void{self::$scheduled[]=$t;}public static function schedule_reconciliation():void{}public static function sync_row_reflection(array $r):bool{self::$synced[$r['idempotency_key']]=$r['status'];if(self::$mutateDuringSyncKey===$r['idempotency_key']){global $wpdb;$id=(int)$r['id'];$wpdb->rows[$id]['status']='sent';$wpdb->rows[$id]['updated_at']='2099-01-01 00:00:00';self::$mutateDuringSyncKey='';}return true;}public static function live_capture_cutoff():array{return['valid'=>true,'timestamp'=>0];}public static function iso_to_timestamp(string $v):int{return strtotime($v)?:0;}public static function config_string(string $n,string $d=''):string{return$d;}public static function validate_event_payload(array $p,string $s='queued',string $e=''):array{return['valid'=>true,'reason'=>''];}}
class IDG_Traceability_Client{public static array $responses=[];public static array $calls=[];public function send(array $p):array{self::$calls[]=$p['idempotency_key'];return array_shift(self::$responses)??['success'=>true,'retry'=>false,'http_status'=>201,'code'=>'traceability_event_recorded','message'=>'ok'];}}
function absint($v){return abs((int)$v);}function get_option($k,$d=false){return$GLOBALS['options'][$k]??$d;}function update_option($k,$v,$a=false){$GLOBALS['options'][$k]=$v;return true;}function sanitize_text_field($v){return trim((string)$v);}function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$v));}function wp_strip_all_tags($v){return strip_tags((string)$v);}function wp_json_encode($v,$f=0){return json_encode($v,$f);}function wp_generate_password($l=12,$s=true,$e=false){static$n=0;return str_pad('lock'.++$n,$l,'x');}
require_once dirname(__DIR__).'/includes/class-traceability-outbox.php';
function ok($c,$m){if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo"OK: $m\n";}
function payload(string $t,string $k,int $b,string $w,string $o='2026-07-05T10:00:00Z'):array{$post=str_starts_with($t,'wordpress_')?9001:null;return['event_type'=>$t,'brief_id'=>$b,'occurred_at'=>$o,'observed_at'=>'2026-07-05T10:00:01Z','source_system'=>$t==='gerizim_imported'?'gerizim-wordpress':'wordpress','source_record_id'=>$t==='gerizim_imported'?$w:(string)$post,'workflow_id'=>$w,'wordpress_post_id'=>$post,'wordpress_status'=>$t==='wordpress_post_created'?'pending':($t==='wordpress_published'?'publish':null),'idempotency_key'=>$k,'evidence_payload'=>['contract_version'=>'1.1'],'actor'=>$t==='wordpress_published'?'wordpress':'ideasdi-redaccion-gerizim'];}
$w='idg_chain';$ik="gerizim_imported:900:$w";$ck="wordpress_post_created:$w:9001";$pk="wordpress_published:$w:9001";IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$ik,900,$w));IDG_Traceability_Outbox::insert_event(payload('wordpress_post_created',$ck,900,$w),'queued',$ik);IDG_Traceability_Outbox::insert_event(payload('wordpress_published',$pk,900,$w),'queued',$ck);IDG_Traceability_Client::$responses=array_fill(0,3,['success'=>true,'retry'=>false,'http_status'=>201,'code'=>'traceability_event_recorded','message'=>'ok']);for($i=0;$i<3;$i++)IDG_Traceability_Outbox::process_queue(10);ok(IDG_Traceability_Client::$calls===[$ik,$ck,$pk],'orden causal persiste entre ejecuciones');ok(IDG_Traceability_Outbox::get_by_key($pk)['status']==='sent','cadena completa enviada');
// Starvation: many blocked children must not hide a later ready root.
for($i=0;$i<30;$i++){IDG_Traceability_Outbox::insert_event(payload('wordpress_post_created',"wordpress_post_created:idg_block$i:9001",1000+$i,"idg_block$i"),'queued',"gerizim_imported:missing$i:idg_block$i");}$ready='gerizim_imported:9999:idg_ready';IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$ready,9999,'idg_ready'));IDG_Traceability_Client::$responses[]=['success'=>true,'retry'=>false,'http_status'=>201,'code'=>'traceability_event_recorded','message'=>'ok'];IDG_Traceability_Outbox::process_queue(1);ok(end(IDG_Traceability_Client::$calls)===$ready,'consulta anti-starvation entrega raíz lista posterior');
$rk='gerizim_imported:901:idg_retry';IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$rk,901,'idg_retry'));for($i=1;$i<=8;$i++){IDG_Traceability_Client::$responses[]=['success'=>false,'retry'=>true,'http_status'=>500,'code'=>'server_error','message'=>'HTTP 500'];foreach($wpdb->rows as&$r)if($r['idempotency_key']===$rk)$r['next_attempt_at']='2000-01-01 00:00:00';unset($r);IDG_Traceability_Outbox::process_queue(10);} $rr=IDG_Traceability_Outbox::get_by_key($rk);ok($rr['attempts']===8&&$rr['status']==='failed','ocho intentos terminan failed');ok($rr['last_error']==='retry_limit_reached'&&$rr['last_transport_error']==='HTTP 500','límite conserva último transporte');
$base='gerizim_imported:902:idg_same';IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$base,902,'idg_same'));$same=payload('gerizim_imported',$base,902,'idg_same');$same['observed_at']='2026-07-05T12:00:00Z';ok(!empty(IDG_Traceability_Outbox::insert_event($same)['success']),'observed_at ignorado');$conf=IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$base,902,'idg_same','2026-07-05T11:00:00Z'));ok(($conf['message']??'')==='idempotency_payload_conflict','occurred_at distinto produce conflicto');
$send='gerizim_imported:903:idg_send';IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$send,903,'idg_send'));foreach($wpdb->rows as&$r)if($r['idempotency_key']===$send){$r['status']='sending';$r['lock_token']='active';$r['locked_at']=gmdate('Y-m-d H:i:s');}unset($r);$m=new ReflectionMethod(IDG_Traceability_Outbox::class,'set_blocked');$m->setAccessible(true);ok($m->invoke(null,IDG_Traceability_Outbox::get_by_key($send),'dependency_not_sent')===false,'reconciliador no toca sending con lock');
$GLOBALS['options']['idg_traceability_reconcile_reflection_cursor']=0;unset(IDG_Traceability::$synced[$send]);IDG_Traceability_Outbox::reconcile(100);ok(!isset(IDG_Traceability::$synced[$send]),'reconciliación excluye sending con lock activo');
$race='gerizim_imported:905:idg_race';IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$race,905,'idg_race'));foreach($wpdb->rows as&$r)if($r['idempotency_key']===$race){$r['status']='sending';$r['lock_token']='';$r['locked_at']=null;$r['reflection_synced_at']=null;}unset($r);$GLOBALS['options']['idg_traceability_reconcile_reflection_cursor']=0;IDG_Traceability::$mutateDuringSyncKey=$race;IDG_Traceability_Outbox::reconcile(100);$raceRow=IDG_Traceability_Outbox::get_by_key($race);ok($raceRow['status']==='sent'&&$raceRow['reflection_synced_at']===null,'cambio sending a sent durante sincronización no marca reflejo como sincronizado');
$failed='gerizim_imported:904:idg_failed';IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$failed,904,'idg_failed'),'failed','','validation_failed');$fr=IDG_Traceability_Outbox::get_by_key($failed);ok(!empty(IDG_Traceability_Outbox::reactivate_reviewed_event($fr['id'])['success']),'reactivación revisada individual funciona');
$pageKeys=[];for($i=0;$i<25;$i++){ $pageKey='gerizim_imported:'.(2000+$i).':idg_page'.$i; $pageKeys[]=$pageKey; IDG_Traceability_Outbox::insert_event(payload('gerizim_imported',$pageKey,2000+$i,'idg_page'.$i)); unset(IDG_Traceability::$synced[$pageKey]); }
foreach($wpdb->rows as&$r)if(in_array($r['idempotency_key'],$pageKeys,true))$r['reflection_synced_at']=null;unset($r);
$GLOBALS['options']['idg_traceability_reconcile_reflection_cursor']=0;
$rec=IDG_Traceability_Outbox::reconcile(10);ok($rec['reflections']<=10&&!empty($rec['has_more']),'reconciliación está paginada');
IDG_Traceability_Outbox::reconcile(10);IDG_Traceability_Outbox::reconcile(10);
ok(isset(IDG_Traceability::$synced[end($pageKeys)]),'cursor de reconciliación llega a filas de lotes posteriores');
foreach($wpdb->rows as&$r)$r['reflection_synced_at']=$r['updated_at'];unset($r);$GLOBALS['options']['idg_traceability_reconcile_reflection_cursor']=0;$beforeTerminal=count(IDG_Traceability::$synced);IDG_Traceability_Outbox::reconcile(100);$afterTerminal=count(IDG_Traceability::$synced);ok($afterTerminal===$beforeTerminal,'filas terminales ya sincronizadas no se recorren indefinidamente');
echo"PASS outbox integration mock\n";
