<?php
define('ABSPATH',__DIR__.'/');define('IDG_TRACEABILITY_DB_VERSION','1.2.0');define('ARRAY_A','ARRAY_A');
$GLOBALS['options']=[];$GLOBALS['schema_mode']='complete';$GLOBALS['schema_test_key']='';$GLOBALS['fail_version_option']=false;
final class PreparedSchemaQuery{public function __construct(public string $sql,public array $args){}}
final class FakeWpdb{
 public string $prefix='wp_';public string $last_error='';
 public function get_charset_collate():string{return'DEFAULT CHARACTER SET utf8mb4';}
 public function prepare($q,...$a):PreparedSchemaQuery{return new PreparedSchemaQuery($q,$a);}
 private function cols():array{return[
'id'=>['bigint(20) unsigned','NO'],'idempotency_key'=>['varchar(191)','NO'],'event_type'=>['varchar(64)','NO'],'payload_json'=>['longtext','NO'],'status'=>['varchar(20)','NO'],'attempts'=>['smallint(5) unsigned','NO'],'next_attempt_at'=>['datetime','YES'],'last_http_status'=>['smallint(5) unsigned','YES'],'last_error'=>['varchar(500)','NO'],'last_transport_error'=>['varchar(500)','NO'],'created_at'=>['datetime','NO'],'updated_at'=>['datetime','NO'],'sent_at'=>['datetime','YES'],'dependency_key'=>['varchar(191)','NO'],'lock_token'=>['varchar(64)','NO'],'locked_at'=>['datetime','YES'],'reflection_synced_at'=>['datetime','YES'],'reflection_last_error'=>['varchar(500)','NO'],'reflection_attempts'=>['smallint(5) unsigned','NO'],'reflection_last_attempt_at'=>['datetime','YES']];}
 public function get_var($q){$sql=$q instanceof PreparedSchemaQuery?$q->sql:(string)$q;$a=$q instanceof PreparedSchemaQuery?$q->args:[];if(str_contains($sql,'SHOW TABLES LIKE'))return $GLOBALS['schema_mode']==='missing_table'?null:$this->prefix.'idg_traceability_outbox';if(str_contains($sql,'SELECT idempotency_key'))return $GLOBALS['schema_test_key'];return null;}
 public function get_results($q,$m=null):array{$sql=$q instanceof PreparedSchemaQuery?$q->sql:(string)$q;if(str_contains($sql,'SHOW COLUMNS')){$c=$this->cols();if($GLOBALS['schema_mode']==='partial')unset($c['reflection_last_error']);if($GLOBALS['schema_mode']==='bad_type')$c['payload_json']=['varchar(255)','NO'];return array_map(fn($n,$v)=>['Field'=>$n,'Type'=>$v[0],'Null'=>$v[1]],array_keys($c),array_values($c));}if(str_contains($sql,'SHOW INDEX')){if($GLOBALS['schema_mode']==='missing_index')return[];$defs=[['PRIMARY',0,['id']],['idempotency_key',0,['idempotency_key']],['status_next_attempt',1,['status','next_attempt_at','id']],['dependency_key',1,['dependency_key']],['locked_at',1,['locked_at']],['reflection_sync',1,['reflection_synced_at','updated_at','id']]];$out=[];foreach($defs as[$name,$non,$cols])foreach($cols as$i=>$col)$out[]=['Key_name'=>$name,'Non_unique'=>$non,'Seq_in_index'=>$i+1,'Column_name'=>$col];return$out;}return[];}
 public function query($q){if(!$q instanceof PreparedSchemaQuery)return 0;$sql=$q->sql;$a=$q->args;if(str_starts_with(trim($sql),'INSERT INTO')){if($GLOBALS['schema_mode']==='write_fail'){$this->last_error='write failed';return false;}$GLOBALS['schema_test_key']=(string)$a[0];return 1;}if(str_starts_with(trim($sql),'DELETE FROM')){$GLOBALS['schema_test_key']='';return 1;}return 0;}
}
$wpdb=new FakeWpdb();$GLOBALS['wpdb']=$wpdb;
class IDG_Traceability{public static function config_string(string $n,string $d=''):string{return$d;}public static function sync_row_reflection(array $r):bool{return true;}public static function live_capture_cutoff():array{return['valid'=>true,'timestamp'=>0];}public static function iso_to_timestamp(string $v):int{return strtotime($v)?:0;}}
function get_option($k,$d=false){return$GLOBALS['options'][$k]??$d;}function update_option($k,$v,$a=false){if($k==='idg_traceability_db_version'&&!empty($GLOBALS['fail_version_option']))return false;$GLOBALS['options'][$k]=$v;return true;}function sanitize_text_field($v){return(string)$v;}function wp_strip_all_tags($v){return strip_tags((string)$v);}function wp_json_encode($v,$f=0){return json_encode($v,$f);} 
require_once dirname(__DIR__).'/includes/class-traceability-outbox.php';
function ok($c,$m){if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo"OK: $m\n";}
$status=IDG_Traceability_Outbox::install_or_upgrade();ok(!empty($status['valid']),'esquema completo se valida');ok(($GLOBALS['options']['idg_traceability_db_version']??'')==='1.2.0','versión DB se guarda después de verificación');ok($GLOBALS['schema_test_key']==='','prueba escritura-lectura-borrado no deja residuo');$sql=$GLOBALS['dbdelta_sql']??'';foreach(['reflection_last_error','reflection_attempts','UNIQUE KEY idempotency_key','status,next_attempt_at,id']as$n)ok(str_contains($sql,$n),"schema contiene $n");
foreach(['dbdelta_error','partial','missing_index','bad_type','write_fail']as$mode){$GLOBALS['schema_mode']=$mode;unset($GLOBALS['options']['idg_traceability_db_version']);$GLOBALS['schema_test_key']='';$s=IDG_Traceability_Outbox::install_or_upgrade();ok(empty($s['valid']),"migración $mode se bloquea");ok(!isset($GLOBALS['options']['idg_traceability_db_version']),"migración $mode no actualiza versión");}
$GLOBALS['schema_mode']='complete';$GLOBALS['fail_version_option']=true;unset($GLOBALS['options']['idg_traceability_db_version']);$s=IDG_Traceability_Outbox::install_or_upgrade();ok(empty($s['valid'])&&in_array('schema_version_persistence_failed',$s['errors']??[],true),'fallo al persistir versión mantiene migración incompleta');ok(!isset($GLOBALS['options']['idg_traceability_db_version']),'versión no se declara instalada si update_option falla');
echo"PASS schema mock\n";
