<?php
define('ABSPATH',__DIR__.'/');define('IDG_TRACEABILITY_CAPTURE_ENABLED',false);define('IDG_TRACEABILITY_DELIVERY_ENABLED',false);define('IDG_TRACEABILITY_CONTRACT_VERSION','1.1');define('IDG_TRACEABILITY_ACTION_HOOK','idg_action');define('IDG_TRACEABILITY_RECONCILE_HOOK','idg_reconcile');
class IDG_Job_Runner{public static array $w=[];public static function get_workflow(string $id):array{return self::$w[$id]??[];}public static function save_workflow(string $id,array $v):void{self::$w[$id]=$v;}}
class IDG_Traceability_Outbox{public static array $rows=[];public static function insert_event(...$a):array{self::$rows[]=$a;return['success'=>true];}public static function schema_status():array{return['valid'=>true,'errors'=>[]];}}
function add_action(...$a){}function sanitize_text_field($v){return trim((string)$v);}function sanitize_key($v){return strtolower(preg_replace('/[^a-z0-9_\-]/','',(string)$v));}function absint($v){return abs((int)$v);}function wp_timezone(){return new DateTimeZone('America/Bogota');}function get_option($k,$d=false){return$d;}function wp_next_scheduled($h){return false;}function wp_schedule_single_event(...$a){}function wp_schedule_event(...$a){}
require_once dirname(__DIR__).'/includes/class-traceability.php';
function ok($c,$m){if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo"OK: $m\n";}
$wid='idg_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';IDG_Job_Runner::$w[$wid]=['workflow_id'=>$wid,'radar_source'=>'radar-editorial-ideasdi','radar_brief_id'=>700,'radar_exported_at'=>'2026-06-01T00:00:00Z','radar_imported_at'=>'2026-07-05 08:00:00'];
$r=IDG_Traceability::persist_radar_import_provenance($wid,700);ok(!empty($r['success']),'captura apagada no impide persistir procedencia');ok(IDG_Job_Runner::$w[$wid]['radar_imported_at_utc']==='2026-07-05T13:00:00Z','fecha local histórica se convierte de forma fiable a UTC');ok(!empty(IDG_Job_Runner::$w[$wid]['radar_import_persisted']),'se guarda marca estructurada');$c=IDG_Traceability::capture_gerizim_imported($wid);ok(($c['reason']??'')==='capture_disabled','captura sigue desactivada');ok(count(IDG_Traceability_Outbox::$rows)===0,'no crea outbox con captura apagada');
$missing='idg_bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';IDG_Job_Runner::$w[$missing]=['workflow_id'=>$missing,'radar_source'=>'radar-editorial-ideasdi','radar_brief_id'=>701,'radar_import_persisted'=>true,'radar_import_identity'=>hash('sha256','radar-editorial-ideasdi|701|'.$missing)];$blocked=IDG_Traceability::persist_radar_import_provenance($missing,701);ok(empty($blocked['success'])&&($blocked['reason']??'')==='invalid_import_occurred_at','workflow existente del mismo brief sin fecha no recibe la hora actual');
echo"PASS provenance disabled mock\n";
